# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
              SCAN_DEVICE: iPhone 8
              SCAN_SCHEME: sample_ci
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  simple-worklfow:
    jobs:
      - build-and-test
