default_platform :ios


platform :ios do

	before_all do
    	setup_circle_ci
  	end
	
    desc 'Build project and executes unit tests'
    lane :unit_test do |option|
	scan(
	  clean: option[:clean],
	  skip_package_dependencies_resolution: option[:skip_package_dependencies_resolution]
     )  
   end
end
